2025-07-29 13:19:10.969340 - User: Anonymous - Path: /admin/login/
2025-07-29 13:19:31.659940 - User: Anonymous - Path: /
2025-07-29 13:19:31.684569 - User: Anonymous - Path: /swagger/
2025-07-29 13:19:33.090678 - User: Anonymous - Path: /swagger/
view's ConversationViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2688, in to_python
    return uuid.UUID(**{input_form: value})
  File "/usr/lib/python3.8/uuid.py", line 168, in __init__
    hex = hex.replace('urn:', '').replace('uuid:', '')
AttributeError: 'AnonymousUser' object has no attribute 'replace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/home/citrondev/prodev_be/alx-backend-python/Django-Middleware-0x03/chats/views.py", line 20, in get_queryset
    return Conversation.objects.filter(participants=self.request.user)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1546, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1577, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1492, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1319, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2672, in get_prep_value
    return self.to_python(value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2690, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ['“AnonymousUser” is not a valid UUID.']
view's MessageViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2688, in to_python
    return uuid.UUID(**{input_form: value})
  File "/usr/lib/python3.8/uuid.py", line 168, in __init__
    hex = hex.replace('urn:', '').replace('uuid:', '')
AttributeError: 'AnonymousUser' object has no attribute 'replace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/home/citrondev/prodev_be/alx-backend-python/Django-Middleware-0x03/chats/views.py", line 41, in get_queryset
    return Message.objects.filter(conversation__participants=self.request.user)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1546, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1577, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1492, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1319, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2672, in get_prep_value
    return self.to_python(value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2690, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ['“AnonymousUser” is not a valid UUID.']
view's MessageViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2688, in to_python
    return uuid.UUID(**{input_form: value})
  File "/usr/lib/python3.8/uuid.py", line 168, in __init__
    hex = hex.replace('urn:', '').replace('uuid:', '')
AttributeError: 'AnonymousUser' object has no attribute 'replace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/home/citrondev/prodev_be/alx-backend-python/Django-Middleware-0x03/chats/views.py", line 41, in get_queryset
    return Message.objects.filter(conversation__participants=self.request.user)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1546, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1577, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1492, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1319, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2672, in get_prep_value
    return self.to_python(value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2690, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ['“AnonymousUser” is not a valid UUID.']
view's ConversationViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2688, in to_python
    return uuid.UUID(**{input_form: value})
  File "/usr/lib/python3.8/uuid.py", line 168, in __init__
    hex = hex.replace('urn:', '').replace('uuid:', '')
AttributeError: 'AnonymousUser' object has no attribute 'replace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/home/citrondev/prodev_be/alx-backend-python/Django-Middleware-0x03/chats/views.py", line 20, in get_queryset
    return Conversation.objects.filter(participants=self.request.user)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1546, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1577, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1492, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1319, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2672, in get_prep_value
    return self.to_python(value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2690, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ['“AnonymousUser” is not a valid UUID.']
view's MessageViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2688, in to_python
    return uuid.UUID(**{input_form: value})
  File "/usr/lib/python3.8/uuid.py", line 168, in __init__
    hex = hex.replace('urn:', '').replace('uuid:', '')
AttributeError: 'AnonymousUser' object has no attribute 'replace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/home/citrondev/prodev_be/alx-backend-python/Django-Middleware-0x03/chats/views.py", line 41, in get_queryset
    return Message.objects.filter(conversation__participants=self.request.user)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1546, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1577, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1492, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1319, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2672, in get_prep_value
    return self.to_python(value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2690, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ['“AnonymousUser” is not a valid UUID.']
view's MessageViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2688, in to_python
    return uuid.UUID(**{input_form: value})
  File "/usr/lib/python3.8/uuid.py", line 168, in __init__
    hex = hex.replace('urn:', '').replace('uuid:', '')
AttributeError: 'AnonymousUser' object has no attribute 'replace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/home/citrondev/prodev_be/alx-backend-python/Django-Middleware-0x03/chats/views.py", line 41, in get_queryset
    return Message.objects.filter(conversation__participants=self.request.user)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1546, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1577, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1492, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1319, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2672, in get_prep_value
    return self.to_python(value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2690, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ['“AnonymousUser” is not a valid UUID.']
view's ConversationViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2688, in to_python
    return uuid.UUID(**{input_form: value})
  File "/usr/lib/python3.8/uuid.py", line 168, in __init__
    hex = hex.replace('urn:', '').replace('uuid:', '')
AttributeError: 'AnonymousUser' object has no attribute 'replace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/home/citrondev/prodev_be/alx-backend-python/Django-Middleware-0x03/chats/views.py", line 20, in get_queryset
    return Conversation.objects.filter(participants=self.request.user)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1546, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1577, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1492, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1319, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2672, in get_prep_value
    return self.to_python(value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2690, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ['“AnonymousUser” is not a valid UUID.']
view's MessageViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2688, in to_python
    return uuid.UUID(**{input_form: value})
  File "/usr/lib/python3.8/uuid.py", line 168, in __init__
    hex = hex.replace('urn:', '').replace('uuid:', '')
AttributeError: 'AnonymousUser' object has no attribute 'replace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/home/citrondev/prodev_be/alx-backend-python/Django-Middleware-0x03/chats/views.py", line 41, in get_queryset
    return Message.objects.filter(conversation__participants=self.request.user)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1546, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1577, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1492, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1319, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2672, in get_prep_value
    return self.to_python(value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2690, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ['“AnonymousUser” is not a valid UUID.']
view's MessageViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2688, in to_python
    return uuid.UUID(**{input_form: value})
  File "/usr/lib/python3.8/uuid.py", line 168, in __init__
    hex = hex.replace('urn:', '').replace('uuid:', '')
AttributeError: 'AnonymousUser' object has no attribute 'replace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/home/citrondev/prodev_be/alx-backend-python/Django-Middleware-0x03/chats/views.py", line 41, in get_queryset
    return Message.objects.filter(conversation__participants=self.request.user)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1546, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1577, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1492, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1319, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2672, in get_prep_value
    return self.to_python(value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2690, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ['“AnonymousUser” is not a valid UUID.']
view's ConversationViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2688, in to_python
    return uuid.UUID(**{input_form: value})
  File "/usr/lib/python3.8/uuid.py", line 168, in __init__
    hex = hex.replace('urn:', '').replace('uuid:', '')
AttributeError: 'AnonymousUser' object has no attribute 'replace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/home/citrondev/prodev_be/alx-backend-python/Django-Middleware-0x03/chats/views.py", line 20, in get_queryset
    return Conversation.objects.filter(participants=self.request.user)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1546, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1577, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1492, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1319, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2672, in get_prep_value
    return self.to_python(value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2690, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ['“AnonymousUser” is not a valid UUID.']
view's MessageViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2688, in to_python
    return uuid.UUID(**{input_form: value})
  File "/usr/lib/python3.8/uuid.py", line 168, in __init__
    hex = hex.replace('urn:', '').replace('uuid:', '')
AttributeError: 'AnonymousUser' object has no attribute 'replace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/home/citrondev/prodev_be/alx-backend-python/Django-Middleware-0x03/chats/views.py", line 41, in get_queryset
    return Message.objects.filter(conversation__participants=self.request.user)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1546, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1577, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1492, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1319, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2672, in get_prep_value
    return self.to_python(value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2690, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ['“AnonymousUser” is not a valid UUID.']
view's MessageViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2688, in to_python
    return uuid.UUID(**{input_form: value})
  File "/usr/lib/python3.8/uuid.py", line 168, in __init__
    hex = hex.replace('urn:', '').replace('uuid:', '')
AttributeError: 'AnonymousUser' object has no attribute 'replace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/home/citrondev/prodev_be/alx-backend-python/Django-Middleware-0x03/chats/views.py", line 41, in get_queryset
    return Message.objects.filter(conversation__participants=self.request.user)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1546, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1577, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1492, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1319, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2672, in get_prep_value
    return self.to_python(value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2690, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ['“AnonymousUser” is not a valid UUID.']
2025-07-29 13:19:45.375728 - User: Anonymous - Path: /
2025-07-29 13:19:45.502384 - User: Anonymous - Path: /swagger/
2025-07-29 13:19:45.582827 - User: Anonymous - Path: /swagger/
2025-07-29 13:19:53.074598 - User: Anonymous - Path: /swagger/
/home/citrondev/prodev_be/alx-backend-python/Django-Middleware-0x03/messaging_app/settings.py changed, reloading.
2025-07-29 13:48:57.795184 - User: Anonymous - Path: /
2025-07-29 13:48:57.909595 - User: Anonymous - Path: /swagger/
2025-07-29 13:48:59.666313 - User: Anonymous - Path: /swagger/
view's ConversationViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2688, in to_python
    return uuid.UUID(**{input_form: value})
  File "/usr/lib/python3.8/uuid.py", line 168, in __init__
    hex = hex.replace('urn:', '').replace('uuid:', '')
AttributeError: 'AnonymousUser' object has no attribute 'replace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/home/citrondev/prodev_be/alx-backend-python/Django-Middleware-0x03/chats/views.py", line 20, in get_queryset
    return Conversation.objects.filter(participants=self.request.user)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1546, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1577, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1492, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1319, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2672, in get_prep_value
    return self.to_python(value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2690, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ['“AnonymousUser” is not a valid UUID.']
view's MessageViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2688, in to_python
    return uuid.UUID(**{input_form: value})
  File "/usr/lib/python3.8/uuid.py", line 168, in __init__
    hex = hex.replace('urn:', '').replace('uuid:', '')
AttributeError: 'AnonymousUser' object has no attribute 'replace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/home/citrondev/prodev_be/alx-backend-python/Django-Middleware-0x03/chats/views.py", line 41, in get_queryset
    return Message.objects.filter(conversation__participants=self.request.user)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1546, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1577, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1492, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1319, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2672, in get_prep_value
    return self.to_python(value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2690, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ['“AnonymousUser” is not a valid UUID.']
view's MessageViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2688, in to_python
    return uuid.UUID(**{input_form: value})
  File "/usr/lib/python3.8/uuid.py", line 168, in __init__
    hex = hex.replace('urn:', '').replace('uuid:', '')
AttributeError: 'AnonymousUser' object has no attribute 'replace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/home/citrondev/prodev_be/alx-backend-python/Django-Middleware-0x03/chats/views.py", line 41, in get_queryset
    return Message.objects.filter(conversation__participants=self.request.user)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1546, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1577, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1492, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1319, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2672, in get_prep_value
    return self.to_python(value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2690, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ['“AnonymousUser” is not a valid UUID.']
view's ConversationViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2688, in to_python
    return uuid.UUID(**{input_form: value})
  File "/usr/lib/python3.8/uuid.py", line 168, in __init__
    hex = hex.replace('urn:', '').replace('uuid:', '')
AttributeError: 'AnonymousUser' object has no attribute 'replace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/home/citrondev/prodev_be/alx-backend-python/Django-Middleware-0x03/chats/views.py", line 20, in get_queryset
    return Conversation.objects.filter(participants=self.request.user)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1546, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1577, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1492, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1319, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2672, in get_prep_value
    return self.to_python(value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2690, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ['“AnonymousUser” is not a valid UUID.']
view's MessageViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2688, in to_python
    return uuid.UUID(**{input_form: value})
  File "/usr/lib/python3.8/uuid.py", line 168, in __init__
    hex = hex.replace('urn:', '').replace('uuid:', '')
AttributeError: 'AnonymousUser' object has no attribute 'replace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/home/citrondev/prodev_be/alx-backend-python/Django-Middleware-0x03/chats/views.py", line 41, in get_queryset
    return Message.objects.filter(conversation__participants=self.request.user)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1546, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1577, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1492, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1319, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2672, in get_prep_value
    return self.to_python(value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2690, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ['“AnonymousUser” is not a valid UUID.']
view's MessageViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2688, in to_python
    return uuid.UUID(**{input_form: value})
  File "/usr/lib/python3.8/uuid.py", line 168, in __init__
    hex = hex.replace('urn:', '').replace('uuid:', '')
AttributeError: 'AnonymousUser' object has no attribute 'replace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/home/citrondev/prodev_be/alx-backend-python/Django-Middleware-0x03/chats/views.py", line 41, in get_queryset
    return Message.objects.filter(conversation__participants=self.request.user)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1546, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1577, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1492, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1319, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2672, in get_prep_value
    return self.to_python(value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2690, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ['“AnonymousUser” is not a valid UUID.']
view's ConversationViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2688, in to_python
    return uuid.UUID(**{input_form: value})
  File "/usr/lib/python3.8/uuid.py", line 168, in __init__
    hex = hex.replace('urn:', '').replace('uuid:', '')
AttributeError: 'AnonymousUser' object has no attribute 'replace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/home/citrondev/prodev_be/alx-backend-python/Django-Middleware-0x03/chats/views.py", line 20, in get_queryset
    return Conversation.objects.filter(participants=self.request.user)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1546, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1577, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1492, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1319, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2672, in get_prep_value
    return self.to_python(value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2690, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ['“AnonymousUser” is not a valid UUID.']
view's MessageViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2688, in to_python
    return uuid.UUID(**{input_form: value})
  File "/usr/lib/python3.8/uuid.py", line 168, in __init__
    hex = hex.replace('urn:', '').replace('uuid:', '')
AttributeError: 'AnonymousUser' object has no attribute 'replace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/home/citrondev/prodev_be/alx-backend-python/Django-Middleware-0x03/chats/views.py", line 41, in get_queryset
    return Message.objects.filter(conversation__participants=self.request.user)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1546, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1577, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1492, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1319, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2672, in get_prep_value
    return self.to_python(value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2690, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ['“AnonymousUser” is not a valid UUID.']
view's MessageViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2688, in to_python
    return uuid.UUID(**{input_form: value})
  File "/usr/lib/python3.8/uuid.py", line 168, in __init__
    hex = hex.replace('urn:', '').replace('uuid:', '')
AttributeError: 'AnonymousUser' object has no attribute 'replace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/home/citrondev/prodev_be/alx-backend-python/Django-Middleware-0x03/chats/views.py", line 41, in get_queryset
    return Message.objects.filter(conversation__participants=self.request.user)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1546, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1577, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1492, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1319, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2672, in get_prep_value
    return self.to_python(value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2690, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ['“AnonymousUser” is not a valid UUID.']
view's ConversationViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2688, in to_python
    return uuid.UUID(**{input_form: value})
  File "/usr/lib/python3.8/uuid.py", line 168, in __init__
    hex = hex.replace('urn:', '').replace('uuid:', '')
AttributeError: 'AnonymousUser' object has no attribute 'replace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/home/citrondev/prodev_be/alx-backend-python/Django-Middleware-0x03/chats/views.py", line 20, in get_queryset
    return Conversation.objects.filter(participants=self.request.user)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1546, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1577, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1492, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1319, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2672, in get_prep_value
    return self.to_python(value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2690, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ['“AnonymousUser” is not a valid UUID.']
view's MessageViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2688, in to_python
    return uuid.UUID(**{input_form: value})
  File "/usr/lib/python3.8/uuid.py", line 168, in __init__
    hex = hex.replace('urn:', '').replace('uuid:', '')
AttributeError: 'AnonymousUser' object has no attribute 'replace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/home/citrondev/prodev_be/alx-backend-python/Django-Middleware-0x03/chats/views.py", line 41, in get_queryset
    return Message.objects.filter(conversation__participants=self.request.user)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1546, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1577, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1492, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1319, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2672, in get_prep_value
    return self.to_python(value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2690, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ['“AnonymousUser” is not a valid UUID.']
view's MessageViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2688, in to_python
    return uuid.UUID(**{input_form: value})
  File "/usr/lib/python3.8/uuid.py", line 168, in __init__
    hex = hex.replace('urn:', '').replace('uuid:', '')
AttributeError: 'AnonymousUser' object has no attribute 'replace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/home/citrondev/prodev_be/alx-backend-python/Django-Middleware-0x03/chats/views.py", line 41, in get_queryset
    return Message.objects.filter(conversation__participants=self.request.user)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1546, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1577, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1492, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1319, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2672, in get_prep_value
    return self.to_python(value)
  File "/home/citrondev/prodev_be/alx-backend-python/messaging_app/messapp_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2690, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ['“AnonymousUser” is not a valid UUID.']
2025-07-29 13:49:41.983712 - User: Anonymous - Path: /swagg
Not Found: /swagg
/home/citrondev/prodev_be/alx-backend-python/Django-Middleware-0x03/chats/middleware.py changed, reloading.
/home/citrondev/prodev_be/alx-backend-python/Django-Middleware-0x03/messaging_app/settings.py changed, reloading.
/home/citrondev/prodev_be/alx-backend-python/Django-Middleware-0x03/manage.py changed, reloading.
/home/citrondev/prodev_be/alx-backend-python/Django-Middleware-0x03/chats/middleware.py changed, reloading.
/home/citrondev/prodev_be/alx-backend-python/Django-Middleware-0x03/messaging_app/settings.py changed, reloading.
/home/citrondev/prodev_be/alx-backend-python/Django-Middleware-0x03/chats/middleware.py changed, reloading.
/home/citrondev/prodev_be/alx-backend-python/Django-Middleware-0x03/messaging_app/settings.py changed, reloading.
/home/citrondev/prodev_be/alx-backend-python/Django-Middleware-0x03/chats/middleware.py changed, reloading.
